### ISSUE TITLE
Licensing ?

### ISSUE THREAD

**Issue by kir0ul** [dattalab/dopamine-reinforces-spontaneous-behavior#3]
Hi,
I was wondering what is the license associated with this repo?
[As far as I understand, if there is no license, apart from viewing the code, one has no rights to do anything with the code.](https://opensource.stackexchange.com/a/1721/9385)
If that's of interest, here's a website that may help to choose a license: https://choosealicense.com/.

**Comment by jmarkow** [comment]
Thanks for the heads up! Addressed in #4 .
