### ISSUE TITLE
dlight_usages_offline_features.parquet file not found

### ISSUE THREAD

**Issue by jlindsey15** [dattalab/dopamine-reinforces-spontaneous-behavior#5]
Hi!  Thanks so much for making this code/data available.  In the all_behavior_00_statemap_and_syllable_stats.ipynb notebook there is a line that loads the file "dlight_usages_offline_features.parquet" -- but this throws an error for me, saying that the file is not present.  I don't see that file in the data, even after preprocessing with _reformat_zenodo_downloads.ipynb.  Am I missing something?

**Comment by jlindsey15** [comment]
Apologies, I believe this issue is due to my running the notebooks in the incorrect order.

**Comment by jmarkow** [comment]
No problem! Feel free to offer suggestions or PRs that might clarify this in the README file so folks aren't tripped up by this in the future.
